### ISSUE TITLE
Broken project at Kinect v2/WPF/VitruviusTest

### ISSUE THREAD

**Issue by birbilis** [LightBuzz/Vitruvius#11]
I see under Kinect v2/WPF/VitruviusTest folder just a .csproj and a .xaml.cs file (not any .xaml or other files). I see the .xaml.cs contains Kinect v2 related-code (MultiFrameSourceReader is Kinect v2 only I think) so it shouldn't be just a remainder from the VitruviusTest folder of the Kinect v1 solution

I there a chance you've forgotten to push some files from that folder to the repository?

**Comment by birbilis** [comment]
btw the respective solution doesn't include that project

**Comment by birbilis** [comment]
other strange folders, this time at WinRT version are 
- Vitruvius.sln.ide: not sure what this is
-  VitruviusTest again, but this time it contains other files, all of which seem to exist in Samples folder, but they have differences looking at them with WinMerge

**Comment by Vangos** [comment]
Cleaned the project and removed the unnecessary files.
