### ISSUE TITLE
GreenScreen sample on WPF is not working

### ISSUE THREAD

**Issue by elbruno** [LightBuzz/Vitruvius#15]
Hi 
In the sample project, raises an "null" error on [GreenScreenBitmapGenerator.cs]

line 196
Marshal.Copy(Pixels, 0, Bitmap.BackBuffer, _displayPixels.Length);

for Pixels

regards

**Comment by birbilis** [comment]
maybe they're not yet ready at that point in time?

if you add a null check somewhere near there does it work?

**Comment by Vangos** [comment]
This was a typo from a previous commit. Thanks for noting. The issue has been fixed.
