### ISSUE TITLE
using vitruvius library

### ISSUE THREAD

**Issue by rahulsiwach** [LightBuzz/Vitruvius#23]
i am already working on a project with kinect and now i want to use your library in that project. I am new to kinect so can you guide me through steps need to be done to add your library in my project.

**Comment by birbilis** [comment]
I believe the best way to add Vitruvius to a project is to use the compiled assemblies via a NuGet package, however for first trying it out you'd better use "download zip" option from GitHub to get the source and the samples and try them

**Comment by rahulsiwach** [comment]
big thnx for such quick help ,I tried again and finally it worked. i will be using it in my project and will be asking more questions about it in future.......hehe
