### ISSUE TITLE
kinect and arduino

### ISSUE THREAD

**Issue by rahulsiwach** [LightBuzz/Vitruvius#24]
can I stream real time data from kinect to mobile phone through internet and control kinect from mobile using arduino??.....thnx in advance

**Comment by birbilis** [comment]
1) The Kinect assemblies themselves aren't in PCL (Portable Class Library) format I think, so to use the same types from a Windows Phone (or other phone via Xamarin's C#), you'd have to copy-paste their definitions and make your own assembly with same namespace to use on the phone.

You'd have to serialize the data types (say into XML or JSON) and deserialize them at the other end of the wire. This has some extra penalty though in time, so it might have some lag. Could also opt to use some binary serialization format for more speed

2) When you say control Kinect via Arduino, do you mean setting some parameters of Kinect via commands send from Arduino? Kinect is a sensor and it doesn't have an actuator apart from turning say IR illumination on/off (Kinect v1 also had a tilt motor, but it is removed in Kinect v2 which has a wider field of view). If you mean the other way arround, to read Kinect data from Arduino, it should be possible too (see [1] above), but a bit harder to process skeleton stream etc. data on Arduino, it's quite slow and just a controller. Best bet would be to do most of your logic on the PC via a .NET process that talks to Kinect and communicates to Arduino via the virtual serial port it defines over its USB connection (there are APIs in .NET to read/write from/to the serial port). Could also make it untethered, via XBee or some more expensive Arduinos that have Wifi-based connection to the PC (think you still use the virtual serial port in that case, no need to mess with TCP/IP)

**Comment by Vangos** [comment]
Hello. You can't connect Kinect to an Arduino board directly. However, you can transmit Kinect data over the network.

**Comment by rahulsiwach** [comment]
i meant to ask that only may be my question was wrong farmed .Still thnx to u both

**Comment by Vangos** [comment]
We are glad we could help you :-)
