### ISSUE TITLE
warning on runtime

### ISSUE THREAD

**Issue by rahulsiwach** [LightBuzz/Vitruvius#25]
giving warning on using code of hand tracking from your blog and using it in other programme. 
Severity	Code	Description	Project	File	Line	Suppression State
Warning		"There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "LightBuzz.Vitruvius, Version=1.0.0.0, Culture=neutral, processorArchitecture=AMD64", "AMD64". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project."	rahul_1			

on using release this warning is coming and there are no errors in code but  the colour image in not appearing in the window, it is coming blank
on using debug this warning is not coming but still no colour image is coming.
kinect sensor is not starting in either case

**Comment by birbilis** [comment]
There is a prefer 32-bit flag in your project build settings. I remember I had issue with a Kinect v1 project. Try toggling it

**Comment by Vangos** [comment]
It's too generic, but if you are deploying a Windows Store (WinRT) app, you need to explicitly set your target to "x86" or "x64".

**Comment by rahulsiwach** [comment]
basically the main problem is I am using this code to get colour image and no error or warning is coming but on running no colour stream is coming nor the kinect sensor is getting started(3 lights don't lit up).......
this is my code(your code from handtracking)..............

namespace rahul_1
{
    /// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class MainWindow : Window
    {
        
        #region Members

        KinectSensor _sensor;
        MultiSourceFrameReader _reader;
        #endregion

        #region Constructor

        public MainWindow()
        {
            InitializeComponent();
        }

        #endregion

        #region Event handlers

        private void Window_Loaded(object sender, RoutedEventArgs e)
        {
            _sensor = KinectSensor.GetDefault();

            if (_sensor != null)
            {
                _sensor.Open();

                _reader = _sensor.OpenMultiSourceFrameReader(FrameSourceTypes.Color | FrameSourceTypes.Depth | FrameSourceTypes.Infrared | FrameSourceTypes.Body);
                _reader.MultiSourceFrameArrived += Reader_MultiSourceFrameArrived;
            }
        }

        private void Window_Closed(object sender, EventArgs e)
        {
            if (_reader != null)
            {
                _reader.Dispose();
            }

            if (_sensor != null)
            {
                _sensor.Close();
            }
        }

        void Reader_MultiSourceFrameArrived(object sender, MultiSourceFrameArrivedEventArgs e)
        {
            var reference = e.FrameReference.AcquireFrame();

            // Color
            using (var frame = reference.ColorFrameReference.AcquireFrame())
            {
                if (frame != null)
                {
                    camera.Source = frame.ToBitmap();
                }
            }
        }

        #endregion
    }
}


Xaml code is..........


<Window x:Class="rahul_1.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:rahul_1"
        mc:Ignorable="d"
        Title="MainWindow" Height="350" Width="525">
    <Grid>
        <Viewbox>
            <Image x:Name="camera" HorizontalAlignment="Left" Height="185" Margin="61,67,0,0" VerticalAlignment="Top" Width="397"/>
        </Viewbox>
    </Grid>
</Window>

**Comment by birbilis** [comment]
Are the samples working ok for you?

**Comment by rahulsiwach** [comment]
yes it is working fine
absolutely perfect

**Comment by birbilis** [comment]
Can you post your project to try it?

**Comment by rahulsiwach** [comment]
my 1st part of project is exactly like camera UI in your sample code, just difference is that instead of bodyskeleton i want to show face gestures(as in face basics sdk 2.0) using vitruvius library.
since for 4 weeks i am stuck with library i am running low on time. so kindly look into this.

**Comment by rahulsiwach** [comment]
yipee......it worked thnx very much u kept me going till now.....and problem till now was with extension file

**Comment by birbilis** [comment]
Shouldn't this issue be closed?

**Comment by Vangos** [comment]
It should be closed. The author reopened.

**Comment by birbilis** [comment]
Probably did by accident
