### ISSUE TITLE
Project not run in visual studio for kinect v2

### ISSUE THREAD

**Issue by aa786g** [LightBuzz/Vitruvius#3]
hello guys, how are you doing today.Actually i've a problem the project you are given is not open in compile in visual studio. it gives me a error. it says add an executable project to this solution which reference the library project. Please help me how i slove this..!!!

**Comment by Vangos** [comment]
Hi @aa786g . Navigate to the Solution Explorer and right-click VitruviusTest. Select "Set as startup project" and you are all set :)

**Comment by aa786g** [comment]
thank you so much for helping me sir

**Comment by aa786g** [comment]
static int NumberOfTrackedJoints(params Joint[] joints)
        {
            return NumberOfTrackedJoints(joints);
        }

in the above code when i stand in front of kinect its gives the exception overflow error..!!

**Comment by Vangos** [comment]
Thank you very much for spotting this out! We have just updated the source code. For your reference, the method should be:

static int NumberOfTrackedJoints(params Joint[] joints)
{
return NumberOfTrackedJoints(joints.ToList());
}
