### ISSUE TITLE
Rename solutions/projects to show target platform

### ISSUE THREAD

**Issue by birbilis** [LightBuzz/Vitruvius#8]
I think it would be better if the solutions (.sln files) were renamed to be for example 
Vitruvius.WPF and Vitruvius.WinRT instead of both being called Vitruvius. For example at the Start page of Visual Studio at recently opened (or at pinned there) solutions you then see two Vitruvius entries which is a bit confusing.

also maybe the solution for Kinect v1 could be renamed to Vitruvius.Kinect1 or something like that

**Comment by Vangos** [comment]
Well, this was our initial naming convention, back in 2012. We had Vitruvius.WPF and Vitruvius.WinForms at the time. Turns out, people do a lot of copy-paste, so we preferred keeping the names the same. Moreover, it is much easier to develop a tutorial.
